services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: neo4j_db
    restart: always
    environment:
      NEO4J_AUTH: neo4j/yourStrongPassword123
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
    ports:
      - "7474:7474"   # Neo4j browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import

  app:
    build: ./app
    container_name: fastapi_app
    depends_on:
      - postgres
      - neo4j
    volumes:
      - ./app:/app
    working_dir: /app
    command: [ "bash", "start.sh" ]
    ports:
      - "8000:8000"

  checks:
    build: ./scripts
    container_name: checks
    depends_on:
      - app
      - postgres
      - neo4j
    volumes:
      - ./app:/work/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=shop
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=yourStrongPassword123

volumes:
  pgdata: